# Generated by Django 3.1.4 on 2020-12-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodos', '0002_auto_20201209_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='add_todo',
            new_name='todo',
        ),
    ]
